= diffamr_bringup

== config dosyaları

- link:configs/cob_scan_unifier.yaml[] : loop_rate ve birleştirilecek scan verilerini içeren input_scans parametreleri ayarlanmıştır.


== launch dosyaları

- link:launch/diffamr_bringup.launch[] : robotun urdf dosyasını robot_description parametresi ile yükler. Ön ve arka lidarlar için farklı namespaceler altında, sick_safetyscanners_node düğümünü çalıştırır. Realsense D435i ve T265 başlatmak için gerekli olan launch dosyalarını çalıştırır. 

[source, bash]
----
roslaunch diffamr_bringup diffamr_bringup.launch
----

- link:launch/diffamr_cob_scan_unifier.launch[] : cob_scan_unifier.yaml dosyası ile birlikte scan_unifier_node düğümünü çalıştırır. Lidar topiklerini birleştirilerek tek bir topik olarak yayınlar.

[source, bash]
----
roslaunch diffamr_bringup diffamr_cob_scan_unifier.launch
----

- link:launch/diffamr_ira_laser_tool.launch[] : uygun parametre değerleriyle beraber laserscan_multi_merger düğümünü çalıştırır. cob_scan_unifier gibi tüm lidar topiklerini birleştirerek tek bir düğüm üzerinden yayınlar.

[source, bash]
----
roslaunch diffamr_bringup diffamr_ira_laser_tool.launch
----

=== cob_scan_unifier çalıştırma

diffamr_cob_scan_unifier.launch dosyası çalıştırıldığında birleştirme işleminin başarısız olduğu görülmüştür. Bunun sonucunda cob_scan_unifier paketinin kaynak kodu incelenmiştir. cob_scan_unifier.yaml dosyasında tanımlanan topiklerin parametre servera /input_scans olarak yüklendiği ancak kaynak kodun parametreleri input_scans olarak aldığı görülmüştür. 

Bu hatayı gidermek için https://github.com/ipa320/cob_driver adresindeki cob_driver paketi catkin_ws/src klasörü içerisine indirilmiştir. Sadece cob_scan_unifier paketi kullanıldığı için diğer paketler kaldırılmıştır. cob_scan_unifier paketindeki scan_unifier_node.cpp düğümünün 132. satırı değiştirilerek sorun giderilmiştir.


[source, bash]
----
  if (pnh_.getParam("input_scans", topicList))
  {
    config_.input_scan_topics = topicList;
    config_.number_input_scans = config_.input_scan_topics.size();
  }
----

"input_scans", "/input_scans" olarak değiştirilmiş ve topik birleştirme işlemi başarılı bir şekilde gerçekleştirilmiştir.