<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="diffamr">

    <xacro:include filename="$(find diffamr_description)/urdf/diffamr.gazebo.xml"/>

    <xacro:property name="base_width" value="0.778"/>
    <xacro:property name="base_len" value="1.198"/>
    <xacro:property name="base_height" value="0.345"/>
    <!-- koruma alanları olmadan değerler -->
    <!-- <xacro:property name="base_width" value="0.707"/>
    <xacro:property name="base_len" value="1.127"/>
    <xacro:property name="base_height" value="0.345"/> -->
    <xacro:property name="wheel_separation" value="0.470"/>
    <xacro:property name="wheel_radius" value="0.08"/>
    <xacro:property name="wheel_width" value="0.06"/>

    <!--Color Properties-->
    <material name="blue">
        <color rgba="0 0 0.8 1"/>
    </material>
    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>
    <material name="white">
        <color rgba="1 1 1 1"/>
    </material>
    <material name="orange">
        <color rgba="0.5 0.2 0.2 1"/>
    </material>
    <material name="silver">
        <color rgba="0.700 0.700 0.700 1.000"/>
    </material>
    <material name="red">
        <color rgba="0.8 0.0 0.0 1.0"/>
    </material>

    <!--Interial macros-->
    <xacro:macro name="cylinder_inertia" params="m r h">
        <inertial>
            <mass value="${m}"/>
            <origin rpy="1.57 0 0" xyz="0 0 0"/>
            <inertia ixx="${m*(3*r*r+h*h)/12}" ixy="0" ixz="0" iyy="${m*(3*r*r+h*h)/12}" iyz="0" izz="${m*r*r/2}"/>
        </inertial>
    </xacro:macro>

    <xacro:macro name="box_inertia" params="m x y z">
        <inertial>
            <mass value="${m}"/>
            <inertia ixx="${m / 12.0 * (y*y + z*z)}" ixy="0.0" ixz="0.0" iyy="${m / 12.0 * (x*x + z*z)}" iyz="0.0"
                     izz="${m / 12.0 * (x*x + y*y)}"/>
        </inertial>
    </xacro:macro>



    <!-- <link name="base_link">

        <inertial>
            <origin rpy="0 0 0" xyz="6.528417638897144e-05 -7.723918885781537e-07 0.12387969606910008"/>
            <mass value="232.39988687241697"/>
            <inertia ixx="11.05" ixy="-0.000000011718" ixz="-0.000374" iyy="27.16" iyz="-0.000003745266" izz="33.63"/>
        </inertial>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 -0.1"/> 
            <geometry>
                <mesh filename="package://diffamr_description/meshes/base_link.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 -0.1"/> 
            <geometry>
                <mesh filename="package://diffamr_description/meshes/base_link.stl" scale="0.001 0.001 0.001"/>
            </geometry>
        </collision>
    </link> -->

    <link name="base_link">
      <inertial>
        <origin rpy="0 0 0" xyz="0.0003528963950015804 -0.004334043984325931 0.11719610822734623"/>
        <mass value="183.81240774533836"/>
        <inertia ixx="9.074876" ixy="0.003861" ixz="0.00617" iyy="22.010219" iyz="-0.080847" izz="26.97218"/>
      </inertial>
      <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <mesh filename="package://diffamr_description/meshes/base_link.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="silver"/>
      </visual>
      <collision>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <mesh filename="package://diffamr_description/meshes/base_link.stl" scale="0.001 0.001 0.001"/>
        </geometry>
      </collision>
    </link>
      
    <link name="base_footprint"/>

    <joint name="base_footprint_joint" type="fixed">
        <origin xyz="0 0 ${wheel_radius+0.02}" rpy="0 0 0" />
        <parent link="base_footprint" />
        <child link="base_link" />
    </joint>
 
    <!--lidar-->
    <xacro:include filename="$(find diffamr_description)/urdf/accessories/sicknanoscan.xacro"/>
    <xacro:sicknanoscan reflect="-1" prefix = "rear" reflect_yaw ="3.1415926535"/>
    <xacro:sicknanoscan reflect="1" prefix = "front" reflect_yaw ="0"/>

    <!--cameras-->
    <xacro:include filename="$(find diffamr_description)/urdf/accessories/d435i.urdf.xacro"/>
    <xacro:d435i/>

    <xacro:include filename="$(find diffamr_description)/urdf/accessories/t265.urdf.xacro"/>
    <xacro:t265/>


    <!--Wheel link & joint macro-->
    <xacro:include filename="$(find diffamr_description)/urdf/wheel.urdf.xacro"/>

    <!--Create left and right Wheel links/joints-->
    <xacro:wheel prefix="left" reflect="-1"/>
    <xacro:wheel prefix="right" reflect="1"/>

    <xacro:include filename="$(find diffamr_description)/urdf/caster_wheel/caster_top_flat.urdf.xacro"/>
    <xacro:include filename="$(find diffamr_description)/urdf/caster_wheel/caster_wheel_holder.urdf.xacro"/>
    <xacro:include filename="$(find diffamr_description)/urdf/caster_wheel/caster_left_wheel.urdf.xacro"/>
    <xacro:include filename="$(find diffamr_description)/urdf/caster_wheel/caster_right_wheel.urdf.xacro"/>

    <!--Create 4 Caster Wheel links & joints-->
    <xacro:macro name="whole_caster_wheel" params="prefix reflect reflect_x">
        <xacro:caster_top_flat prefix="${prefix}" reflect="${reflect}" reflect_x="${reflect_x}"/>
        <xacro:caster_wheel_holder prefix="${prefix}" reflect="${reflect}" reflect_x="${reflect_x}"/>
        <xacro:caster_left_wheel prefix="${prefix}" reflect="${reflect}" reflect_x="${reflect_x}"/>
        <xacro:caster_right_wheel prefix="${prefix}" reflect="${reflect}" reflect_x="${reflect_x}"/>
    </xacro:macro>

    <xacro:whole_caster_wheel prefix="back_left" reflect="-1" reflect_x="1"/>
    <xacro:whole_caster_wheel prefix="back_right" reflect="1" reflect_x="1"/>
    <xacro:whole_caster_wheel prefix="front_left" reflect="-1" reflect_x="-1"/>
    <xacro:whole_caster_wheel prefix="front_right" reflect="1" reflect_x="-1"/>




</robot>