1:
  id: 1
  category: goal1
  position:
    x: 4.24
    y: -3.98
    z: 0.0
  orientation:
    w: 0.85
    x: 0.0
    y: 0.0
    z: 0.51
2:
  id: 2
  category: goal2
  position:
    x: 2.32
    y: 1.83
    z: 0.0
  orientation:
    w: 0.91
    x: 0.0
    y: 0.0
    z: 0.41
3:
  id: 3
  category: charge
  position:
    x: 8.84
    y: -3.06
    z: 0.0
  orientation:
    w: 0.708
    x: 0.0
    y: 0.0
    z: -0.705