= dowaksa_amr_base

hardware_interface için gerekli düğümleri içerir.

== config dosyaları

- link:config/control.yaml[] : controller_managera yüklemek üzere diff_drive_controller ve joint_state_controller için gerekli olan parametreleri içerir. diff_drive_controller içerisinde ise rampalama ve limitleme işlemlerini gerçekleştirmek için gerekli olan parametrelere uygun değerler atanmıştır. 

== launch dosyaları 

- link:launch/control.launch[] : dowaksa_amr_hardware_interface düğümünü başlatır. control.yaml dosyası ile birlikte controller managera diff_drive_controller ve joint_state_controller yükler.

[source, bash]
----
roslaunch dowaksa_amr_base control.launch
----

== src dosyaları

- link:dowaksa_amr_hardware_interface.cpp[] : dowaksa_amr_hw_node düğümündeki fonksiyonlar ile controller managera okuma,yazma ve update etme işlemleri gerçekleştirilir.

- link:dowaksa_amr_hw_node.cpp[] : 


<1> cds_driverdan yayınlanan motor_pos topiğinin ilk verisi waitForMessage ile alınır. Alınan veri left_wheel.encoder ve rigth_wheel.encoder değişkenlerine atanır.

<2> read fonksiyonu içerisinde motor_pose topiğinden veri alınır. ilk alınan değer ile yeni alınan değer arasındaki farka göre hız hesaplanır. Bu işlem sürekli gerçekleştirilir. Hız verisinin yanı sıra pose verisi de hesaplanır.

<3> diff_drive_controllerdan rad/sn olarak alınan hız verisi rmp'e dönüştürülür. dönüştürülen veri driver_cmd_vel topiği ile yayınlanır.



 

